window.AULALA_ORDER_FEED = {
  "generatedAt": "2026-04-01 12:52:13",
  "source": "fbadidi-erp-api-bridge",
  "rules": {
    "pickupAddress": "悉尼",
    "pickupAddressForPricing": "16 Erskine Road, Caringbah NSW 2229, Australia",
    "pickupCoordinatesForPricing": {
      "lat": -34.0254679,
      "lon": 151.1221244
    },
    "orderApiUrl": "http://121.196.233.99:8080/api/order/getOrderByPutCode",
    "excludedProviders": [
      "TLA"
    ],
    "skippedProviderOrders": [
      {
        "orderCode": "QY04001910BWU2",
        "provider": "TLA"
      },
      {
        "orderCode": "MY10HK000106AU4",
        "provider": "TLA"
      },
      {
        "orderCode": "MY04000060XBW3",
        "provider": "TLA"
      },
      {
        "orderCode": "AY12K000076AU2",
        "provider": "TLA"
      }
    ],
    "cbmPerPallet": 1.5,
    "audPerKmPerPallet": 3.0,
    "minimumPriceAud": 80.0,
    "intrastateRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/2025私人卡派价格.xlsx",
    "zonghengRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/纵横卡派报价表_updated on 22.08.25.xlsx",
    "intrastateCityCode": "SYD",
    "metroRateCardCities": [
      "BNE",
      "MEL",
      "SYD"
    ],
    "zonghengMetroZoneCities": [
      "ADL",
      "BNE",
      "MEL",
      "SYD"
    ],
    "intrastateChargeableRatio": 250.0,
    "intrastateFuelSurchargeRate": 0.1,
    "planArrivalLeadDays": 3,
    "actualArrivalLookbackDays": 16,
    "pickupBusinessTime": "all computed pickup dates are normalized into Australia business time: weekdays only, 10:00-16:00; missing/00:00 times become 10:00, after-hours move to the next business slot",
    "expectedPickupTime": "if actual_arrived_port_time is missing use plan_arrived_port_time + 7 days; if arrived use actual_arrived_port_time + 7 days; whenever an arrived order's computed pickup time is already in the past while the order is still undelivered, move it to now + 1 day; every resulting pickup time is then normalized into Australia business time on a weekday between 10:00 and 16:00; clean rows are shown as confirmed pickup time in green",
    "clearanceStatus": "import_clearance_status is normalized from Tencent cloud values: 2/clean -> clean, 1/held -> held, empty -> pending",
    "eligibility": "pull only orders that are not delivery_completed; if actual_arrived_port_time exists keep rows on or after Australia today minus 16 days, otherwise include rows once Australia today reaches plan_arrived_port_time minus 3 days; then skip providers listed in excludedProviders, currently used to keep TLA-provider orders out of the hall",
    "invoiceData": "dropoff address, weight, cbm, provider, refId, and chargeCode are fetched from the FBADIDI putCode order API first, with the legacy invoice script used only as fallback",
    "priceFormula": "calculate both TLA and Zongheng workbook prices when available, then use the lower one; TLA uses its city zone workbook, Zongheng uses postcode zones plus any interstate truck surcharge based on unload city from destination_port (fallback: crowdfund/warehouse hints); uncovered orders keep max(minimumPriceAud, distanceKm * pallets * audPerKmPerPallet)"
  },
  "orders": [
    {
      "id": 413461,
      "orderCode": "QY06001162AU3",
      "price": 202.25,
      "state": "VIC",
      "pickup": "悉尼",
      "dropoff": "Vermont",
      "pallets": 4,
      "weight": "869kg",
      "time": "01-04 10:00",
      "date": "2026-04-01",
      "pickupAddress": "16 Erskine Road, Caringbah NSW 2229, Australia",
      "dropoffAddress": "5/173-181 Rooks Rd, Vermont, VIC, 3133",
      "pieces": 68,
      "cbm": 6.0,
      "weightKg": 869.0,
      "distanceKm": 878.6,
      "distancePricingBasis": "osrm",
      "pricingModel": "tla_rate_card",
      "pricingVendor": "TLA",
      "destinationPostcode": "3133",
      "chargeableWeightKg": 1500.0,
      "chargeableCbm": 6.0,
      "unloadCityCode": "MEL",
      "tlaRateCardPrice": 202.25,
      "zonghengRateCardPrice": 264.0,
      "distanceFallbackPrice": 10542.62,
      "rateCardVendor": "TLA",
      "rateCardCityCode": "MEL",
      "rateCardZone": "ZONE3",
      "rateCardZoneLabel": "ZONE3",
      "rateCardZoneBasis": "postcode_zone",
      "rateCardZoneMaxKm": 60,
      "rateCardRowMaxKg": 1500.0,
      "rateCardRowMaxCbm": 6.0,
      "rateCardBasePrice": 183.86,
      "rateCardFuelSurchargeRate": 0.1,
      "rateCardFuelSurchargeAud": 18.39,
      "rateCardInterstateFromCityCode": null,
      "rateCardInterstateToCityCode": null,
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": null,
      "rateCardLocalPricePerCbm": null,
      "rateCardLocalMinimumCharge": null,
      "rateCardLocalBillableCbm": null,
      "actualLeavePortTime": "2026-03-08",
      "planArrivedPortTime": "2026-03-25",
      "actualArrivedPortTime": "",
      "importClearanceTime": "",
      "pickupTimeBasis": "plan_arrived_port_time_plus_7_not_arrived",
      "pickupTimeLabel": "预计提货时间",
      "pickupTimeStatus": "estimated",
      "pickupTimeColor": "red",
      "expectedPickupTime": "2026-04-01 10:00",
      "autoOrderEligibilityBasis": "plan_arrived_minus_lead_days_not_arrived",
      "autoOrderEligibilityTriggerTime": "2026-03-22 00:00",
      "autoOrderEligibilityReason": "actual_arrived_port_time missing; now=2026-04-01 12:52 >= trigger=2026-03-22 00:00",
      "clearanceStatus": "held",
      "clearanceStatusRaw": "held",
      "clearanceStatusLabel": "查验中",
      "chargeCode": "",
      "refId": "QY06001162AU3",
      "provider": "SINOLINX",
      "source": "fbadidi_putcode_order_api",
      "sourceRefreshedAt": "2026-03-31 19:48:43"
    },
    {
      "id": 771507,
      "orderCode": "MY06001314AU3",
      "price": 44.0,
      "state": "VIC",
      "pickup": "悉尼",
      "dropoff": "Keysborough",
      "pallets": 1,
      "weight": "65kg",
      "time": "01-04 10:00",
      "date": "2026-04-01",
      "pickupAddress": "16 Erskine Road, Caringbah NSW 2229, Australia",
      "dropoffAddress": "22 Bellarine Court, Keysborough, VIC, 3173",
      "pieces": 3,
      "cbm": 0.36,
      "weightKg": 65.0,
      "distanceKm": 894.5,
      "distancePricingBasis": "osrm",
      "pricingModel": "zongheng_rate_card",
      "pricingVendor": "ZHONGHENG",
      "destinationPostcode": "3173",
      "chargeableWeightKg": 90.75,
      "chargeableCbm": 0.363,
      "unloadCityCode": "MEL",
      "tlaRateCardPrice": 66.86,
      "zonghengRateCardPrice": 44.0,
      "distanceFallbackPrice": 2683.52,
      "rateCardVendor": "ZHONGHENG",
      "rateCardCityCode": "MEL",
      "rateCardZone": "V3",
      "rateCardZoneLabel": "Melbourne-3",
      "rateCardZoneBasis": "postcode_zone",
      "rateCardZoneMaxKm": null,
      "rateCardRowMaxKg": null,
      "rateCardRowMaxCbm": null,
      "rateCardBasePrice": 40.0,
      "rateCardFuelSurchargeRate": 0.1,
      "rateCardFuelSurchargeAud": 4.0,
      "rateCardInterstateFromCityCode": "",
      "rateCardInterstateToCityCode": "",
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": 0.0,
      "rateCardLocalPricePerCbm": 40.0,
      "rateCardLocalMinimumCharge": 40.0,
      "rateCardLocalBillableCbm": 1.0,
      "actualLeavePortTime": "2026-03-08",
      "planArrivedPortTime": "2026-03-25",
      "actualArrivedPortTime": "",
      "importClearanceTime": "",
      "pickupTimeBasis": "plan_arrived_port_time_plus_7_not_arrived",
      "pickupTimeLabel": "预计提货时间",
      "pickupTimeStatus": "estimated",
      "pickupTimeColor": "red",
      "expectedPickupTime": "2026-04-01 10:00",
      "autoOrderEligibilityBasis": "plan_arrived_minus_lead_days_not_arrived",
      "autoOrderEligibilityTriggerTime": "2026-03-22 00:00",
      "autoOrderEligibilityReason": "actual_arrived_port_time missing; now=2026-04-01 12:52 >= trigger=2026-03-22 00:00",
      "clearanceStatus": "held",
      "clearanceStatusRaw": "held",
      "clearanceStatusLabel": "查验中",
      "chargeCode": "-1",
      "refId": "MYH003025",
      "provider": "HUNTER",
      "source": "fbadidi_putcode_order_api",
      "sourceRefreshedAt": "2026-04-01 09:43:01"
    },
    {
      "id": 326526,
      "orderCode": "QY04000193AU2",
      "price": 22.0,
      "state": "NSW",
      "pickup": "悉尼",
      "dropoff": "Lidcombe",
      "pallets": 1,
      "weight": "34kg",
      "time": "30-03 10:00",
      "date": "2026-03-30",
      "pickupAddress": "16 Erskine Road, Caringbah NSW 2229, Australia",
      "dropoffAddress": "69 Yarram St, Lidcombe, NSW, 2141",
      "pieces": 2,
      "cbm": 0.27,
      "weightKg": 34.0,
      "distanceKm": 28.2,
      "distancePricingBasis": "osrm",
      "pricingModel": "tla_rate_card",
      "pricingVendor": "TLA",
      "destinationPostcode": "2141",
      "chargeableWeightKg": 66.5,
      "chargeableCbm": 0.266,
      "unloadCityCode": "MEL",
      "tlaRateCardPrice": 22.0,
      "zonghengRateCardPrice": 79.11,
      "distanceFallbackPrice": 84.59,
      "rateCardVendor": "TLA",
      "rateCardCityCode": "SYD",
      "rateCardZone": "ZONE1",
      "rateCardZoneLabel": "ZONE1",
      "rateCardZoneBasis": "postcode_zone",
      "rateCardZoneMaxKm": 15,
      "rateCardRowMaxKg": 70.0,
      "rateCardRowMaxCbm": 0.28,
      "rateCardBasePrice": 20.0,
      "rateCardFuelSurchargeRate": 0.1,
      "rateCardFuelSurchargeAud": 2.0,
      "rateCardInterstateFromCityCode": null,
      "rateCardInterstateToCityCode": null,
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": null,
      "rateCardLocalPricePerCbm": null,
      "rateCardLocalMinimumCharge": null,
      "rateCardLocalBillableCbm": null,
      "actualLeavePortTime": "",
      "planArrivedPortTime": "2026-03-23",
      "actualArrivedPortTime": "",
      "importClearanceTime": "",
      "pickupTimeBasis": "plan_arrived_port_time_plus_7_not_arrived",
      "pickupTimeLabel": "预计提货时间",
      "pickupTimeStatus": "estimated",
      "pickupTimeColor": "red",
      "expectedPickupTime": "2026-03-30 10:00",
      "autoOrderEligibilityBasis": "plan_arrived_minus_lead_days_not_arrived",
      "autoOrderEligibilityTriggerTime": "2026-03-20 00:00",
      "autoOrderEligibilityReason": "actual_arrived_port_time missing; now=2026-04-01 12:52 >= trigger=2026-03-20 00:00",
      "clearanceStatus": "",
      "clearanceStatusRaw": "",
      "clearanceStatusLabel": "待放行",
      "chargeCode": "-1",
      "refId": "MYH002987",
      "provider": "HUNTER",
      "source": "fbadidi_putcode_order_api",
      "sourceRefreshedAt": "2026-03-23 01:44:37"
    }
  ]
};
