window.AULALA_ORDER_FEED = {
  "generatedAt": "2026-04-06 11:24:33",
  "source": "fbadidi-live-crowdfund-api",
  "rules": {
    "pickupAddress": "悉尼",
    "pickupAddressForPricing": "16 Erskine Road, Caringbah NSW 2229, Australia",
    "pickupCoordinatesForPricing": {
      "lat": -34.0254679,
      "lon": 151.1221244
    },
    "liveCrowdfundSource": "FBADIDI authenticated website APIs: /crowdfund/crowdfund/list -> /crowdfund/crowdfund/{id} -> /crowdfund/tad/listByTadId",
    "requiredDeliveryProvider": "AULALA",
    "orderApiUrl": "http://121.196.233.99:8080/api/order/getOrderByPutCode",
    "orderEnrichWorkers": 8,
    "assignmentOverridesPath": "/root/.openclaw/workspace/data/aulala-assignment-overrides.json",
    "assignmentOverrideCount": 0,
    "excludedProviders": [],
    "skippedProviderOrders": [],
    "crowdfundStartDate": "",
    "cbmPerPallet": 1.5,
    "audPerKmPerPallet": 3.0,
    "minimumPriceAud": 80.0,
    "intrastateRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/2025私人卡派价格.xlsx",
    "zonghengRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/纵横卡派报价表_updated on 22.08.25.xlsx",
    "intrastateCityCode": "SYD",
    "metroRateCardCities": [],
    "zonghengMetroZoneCities": [],
    "intrastateChargeableRatio": 250.0,
    "intrastateFuelSurchargeRate": 0.1,
    "actualArrivalLookbackDays": 16,
    "pickupBusinessTime": "all computed pickup dates are normalized into Australia business time: weekdays only, 10:00-16:00; missing/00:00 times become 10:00, after-hours move to the next business slot",
    "expectedPickupTime": "if TAD already has plan_pickup_time (palnOutTime), use it as the authoritative pickup time; otherwise fall back to actual_arrived_port_time + 7 days, and if that date is already in the past while the order is still undelivered, move it to now + 1 day before normalizing into Australia business time",
    "pickupWarehouseAddress": "if TAD already has outWarehouse and the AULALA warehouse master can resolve it, use that warehouse label and address as the real pickup point for display and pricing; otherwise fall back to the default fixed pickup address",
    "clearanceStatus": "import_clearance_status now comes from live FBADIDI crowdfund/tad rows when available: 2/clean -> clean, 1/held -> held, empty -> pending",
    "crowdfundScanOrder": "scan /crowdfund/crowdfund/list ordered by actualArrivedPortTime desc, starting from Australia today and walking backward; once rows become older than actualArrivalLookbackDays or lose actualArrivedPortTime, stop scanning older crowdfunds",
    "eligibility": "pull only live crowdfund + TAD rows; a row is eligible only when tad.refName is AULALA and putCode is present; TAD.palnOutTime is the first-class pickup-time source, otherwise fall back to crowdfund.actual_arrived_port_time within the current lookback window",
    "invoiceData": "dropoff address, weight, cbm, provider, refId, and chargeCode are fetched from the external putCode order API first, then the authenticated FBADIDI invoice detail APIs, with the legacy invoice script used only as final fallback",
    "priceFormula": "calculate both TLA and Zongheng workbook prices when available, then use the lower one; TLA uses its city zone workbook, Zongheng uses postcode zones plus any interstate truck surcharge based on unload city from destination_port (fallback: crowdfund/warehouse hints); uncovered orders keep max(minimumPriceAud, distanceKm * pallets * audPerKmPerPallet)",
    "assignmentMergeRule": "when a batch-assigned group from the same assignmentSource is already locked to the same driver and shares the same pickup address, dropoff address, and expected pickup time, merge those rows into one delivery order and keep the child putCodes in mergedOrderCodes"
  },
  "orders": [
    {
      "id": 864116,
      "orderCode": "QY08000310AU2",
      "price": 883.6,
      "state": "ACT",
      "pickup": "AULALA(SYD01)",
      "dropoff": "Canberra",
      "pallets": 1,
      "weight": "22kg",
      "time": "07-04 10:00",
      "date": "2026-04-07",
      "pickupAddress": "16 Erskine road Caringbah NSW 2229, Caringbah, NSW, 2229",
      "dropoffAddress": "12 Ammon place Kambah, Canberra, ACT, 2902",
      "pieces": 1,
      "cbm": 0.07,
      "weightKg": 22.0,
      "distanceKm": 294.5,
      "distancePricingBasis": "osrm",
      "pricingModel": "distance_formula",
      "pricingVendor": "DISTANCE_FALLBACK",
      "destinationPostcode": "2902",
      "chargeableWeightKg": 22.0,
      "chargeableCbm": 0.088,
      "unloadCityCode": "SYD",
      "tlaRateCardPrice": null,
      "zonghengRateCardPrice": null,
      "distanceFallbackPrice": 883.6,
      "rateCardVendor": "",
      "rateCardCityCode": "",
      "rateCardZone": "",
      "rateCardZoneLabel": "",
      "rateCardZoneBasis": "",
      "rateCardZoneMaxKm": null,
      "rateCardRowMaxKg": null,
      "rateCardRowMaxCbm": null,
      "rateCardBasePrice": null,
      "rateCardFuelSurchargeRate": null,
      "rateCardFuelSurchargeAud": null,
      "rateCardInterstateFromCityCode": "",
      "rateCardInterstateToCityCode": "",
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": null,
      "rateCardLocalPricePerCbm": null,
      "rateCardLocalMinimumCharge": null,
      "rateCardLocalBillableCbm": null,
      "actualLeavePortTime": "2026-03-16",
      "planPickupTime": "2026-04-07",
      "planArrivedPortTime": "2026-03-28",
      "actualArrivedPortTime": "2026-03-29",
      "importClearanceTime": "",
      "pickupTimeBasis": "tad_plan_pickup_time",
      "pickupTimeLabel": "预计提货时间",
      "pickupTimeStatus": "estimated",
      "pickupTimeColor": "red",
      "expectedPickupTime": "2026-04-07 10:00",
      "autoOrderEligibilityBasis": "tad_plan_pickup_time_and_delivery_provider_aulala",
      "autoOrderEligibilityTriggerTime": "2026-04-07 00:00",
      "autoOrderEligibilityReason": "plan_pickup_time=2026-04-07 00:00 and tad.refName=AULALA",
      "configuredDeliveryProvider": "AULALA",
      "clearanceStatus": "",
      "clearanceStatusRaw": "",
      "clearanceStatusLabel": "待放行",
      "chargeCode": "",
      "refId": "",
      "provider": "AULALA",
      "source": "fbadidi_putcode_order_api",
      "sourceRefreshedAt": "2026-04-05 23:57:26"
    },
    {
      "id": 499620,
      "orderCode": "QY09000252AU2",
      "price": 118.63,
      "state": "NSW",
      "pickup": "AULALA(SYD01)",
      "dropoff": "Baulkham Hills",
      "pallets": 1,
      "weight": "5.85kg",
      "time": "07-04 10:00",
      "date": "2026-04-07",
      "pickupAddress": "16 Erskine road Caringbah NSW 2229, Caringbah, NSW, 2229",
      "dropoffAddress": "37 Woodlands St, Baulkham Hills, NSW, 2153",
      "pieces": 1,
      "cbm": 0.03,
      "weightKg": 5.85,
      "distanceKm": 39.5,
      "distancePricingBasis": "osrm",
      "pricingModel": "distance_formula",
      "pricingVendor": "DISTANCE_FALLBACK",
      "destinationPostcode": "2153",
      "chargeableWeightKg": 8.25,
      "chargeableCbm": 0.033,
      "unloadCityCode": "SYD",
      "tlaRateCardPrice": null,
      "zonghengRateCardPrice": null,
      "distanceFallbackPrice": 118.63,
      "rateCardVendor": "",
      "rateCardCityCode": "",
      "rateCardZone": "",
      "rateCardZoneLabel": "",
      "rateCardZoneBasis": "",
      "rateCardZoneMaxKm": null,
      "rateCardRowMaxKg": null,
      "rateCardRowMaxCbm": null,
      "rateCardBasePrice": null,
      "rateCardFuelSurchargeRate": null,
      "rateCardFuelSurchargeAud": null,
      "rateCardInterstateFromCityCode": "",
      "rateCardInterstateToCityCode": "",
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": null,
      "rateCardLocalPricePerCbm": null,
      "rateCardLocalMinimumCharge": null,
      "rateCardLocalBillableCbm": null,
      "actualLeavePortTime": "2026-03-16",
      "planPickupTime": "2026-04-07",
      "planArrivedPortTime": "2026-03-28",
      "actualArrivedPortTime": "2026-03-29",
      "importClearanceTime": "",
      "pickupTimeBasis": "tad_plan_pickup_time",
      "pickupTimeLabel": "预计提货时间",
      "pickupTimeStatus": "estimated",
      "pickupTimeColor": "red",
      "expectedPickupTime": "2026-04-07 10:00",
      "autoOrderEligibilityBasis": "tad_plan_pickup_time_and_delivery_provider_aulala",
      "autoOrderEligibilityTriggerTime": "2026-04-07 00:00",
      "autoOrderEligibilityReason": "plan_pickup_time=2026-04-07 00:00 and tad.refName=AULALA",
      "configuredDeliveryProvider": "AULALA",
      "clearanceStatus": "",
      "clearanceStatusRaw": "",
      "clearanceStatusLabel": "待放行",
      "chargeCode": "",
      "refId": "",
      "provider": "AULALA",
      "source": "fbadidi_putcode_order_api",
      "sourceRefreshedAt": "2026-04-05 23:57:26"
    }
  ]
};
