window.AULALA_ORDER_FEED = {
  "generatedAt": "2026-03-02 10:00:00",
  "source": "fbadidi-live-crowdfund-api",
  "rules": {
    "replayBasis": "planned_load",
    "pickupAddress": "悉尼",
    "pickupAddressForPricing": "16 Erskine Road, Caringbah NSW 2229, Australia",
    "pickupCoordinatesForPricing": {
      "lat": -34.0254679,
      "lon": 151.1221244
    },
    "liveCrowdfundSource": "FBADIDI authenticated website APIs: /crowdfund/crowdfund/list -> /crowdfund/crowdfund/{id} -> /crowdfund/tad/listByTadId",
    "requiredDeliveryProvider": "AULALA",
    "orderApiUrl": "http://121.196.233.99:8080/api/order/getOrderByPutCode",
    "orderEnrichWorkers": 16,
    "assignmentOverridesPath": "/Users/yangxiaochun/项目/fbadidi/data/aulala-assignment-overrides.json",
    "assignmentOverrideCount": 0,
    "excludedProviders": [],
    "skippedProviderOrders": [],
    "crowdfundStartDate": "",
    "cbmPerPallet": 1.5,
    "audPerKmPerPallet": 3.0,
    "minimumPriceAud": 80.0,
    "intrastateRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/2025私人卡派价格.xlsx",
    "zonghengRateCardPath": "/Users/yangxiaochun/项目/fbadidi/pricing/纵横卡派报价表_updated on 22.08.25.xlsx",
    "intrastateCityCode": "SYD",
    "metroRateCardCities": [
      "BNE",
      "MEL",
      "SYD"
    ],
    "zonghengMetroZoneCities": [
      "ADL",
      "BNE",
      "MEL",
      "SYD"
    ],
    "intrastateChargeableRatio": 250.0,
    "intrastateFuelSurchargeRate": 0.1,
    "actualArrivalLookbackDays": 6,
    "pickupBusinessTime": "all computed pickup dates are normalized into Australia business time: weekdays only, 10:00-16:00; missing/00:00 times become 10:00, after-hours move to the next business slot",
    "expectedPickupTime": "if TAD already has plan_pickup_time (palnOutTime), use it as the authoritative pickup time; otherwise use actual_arrived_port_time + 7 days, or plan_arrived_port_time + 7 days when actual arrival is still empty; if that date is already in the past while the order is still undelivered, move it to now + 1 day before normalizing into Australia business time",
    "pickupWarehouseAddress": "if TAD already has outWarehouse and the AULALA warehouse master can resolve it, use that warehouse label and address as the real pickup point for display and pricing; otherwise fall back to the default fixed pickup address",
    "clearanceStatus": "import_clearance_status now comes from live FBADIDI crowdfund/tad rows when available: 2/clean -> clean, 1/held -> held, empty -> pending",
    "crowdfundScanOrder": "planned_load replay: query /crowdfund/crowdfund/list by crowdfundPlanInstallTime on the target planned-load day, then keep only rows whose crowdfundPlanInstallTime / planTakeCabinetTime / planPickCabinetTime lands on that Australia date",
    "eligibility": "planned_load replay: pull only live crowdfund + TAD rows; a row is eligible only when tad.refName is AULALA, putCode is present, and the crowdfund planned-load date hits the target replay day",
    "invoiceData": "dropoff address, weight, cbm, provider, refId, and chargeCode are fetched from the external putCode order API first, then the authenticated FBADIDI invoice detail APIs, with the legacy invoice script used only as final fallback",
    "priceFormula": "calculate both TLA and Zongheng workbook prices when available, then use the lower one; TLA uses its city zone workbook, Zongheng uses postcode zones plus any interstate truck surcharge based on unload city from destination_port (fallback: crowdfund/warehouse hints); uncovered orders keep max(minimumPriceAud, distanceKm * pallets * audPerKmPerPallet)",
    "autoMergeRule": "before entering the hall, unassigned ERP auto orders that share the same physical pickup address are treated as the same warehouse; when they also share the same dropoff address and expected pickup time, merge them into one hall order; if pickupAddress is missing, fall back to the pickup warehouse label",
    "assignmentMergeRule": "when a batch-assigned group from the same assignmentSource is already locked to the same driver and shares the same pickup address, dropoff address, and expected pickup time, merge those rows into one delivery order and keep the child putCodes in mergedOrderCodes",
    "orderCodeRule": "owner-posted orders use HZ-prefixed codes; non-merged ERP auto orders keep the original putCode; any platform-generated merged order uses a stable ZD-prefixed code derived from the merged child putCodes"
  },
  "orders": [
    {
      "id": 708555,
      "orderCode": "ZD8AF3BD6C",
      "price": 330.47,
      "state": "VIC",
      "pickup": "AULALA(MEL)",
      "dropoff": "Dandenong South",
      "pallets": 8,
      "weight": "358.1kg",
      "time": "07-04 10:00",
      "date": "2026-04-07",
      "pickupAddress": "170 Cherry Ln, Laverton North VIC 3026, Laverton North, VIC, 3026",
      "dropoffAddress": "29 National Drive, Dandenong South, VIC, 3175",
      "pieces": 23,
      "cbm": 3.67,
      "weightKg": 358.1,
      "distanceKm": null,
      "distancePricingBasis": "merged_same_address_auto_hall",
      "pricingModel": "merged_auto_delivery",
      "pricingVendor": "MERGED",
      "destinationPostcode": "3175",
      "chargeableWeightKg": 920.25,
      "chargeableCbm": 3.681,
      "unloadCityCode": "MEL",
      "tlaRateCardPrice": 90.2,
      "zonghengRateCardPrice": 44.0,
      "distanceFallbackPrice": null,
      "rateCardVendor": "MERGED",
      "rateCardCityCode": "MEL",
      "rateCardZone": "V3",
      "rateCardZoneLabel": "Melbourne-3",
      "rateCardZoneBasis": "postcode_zone",
      "rateCardZoneMaxKm": null,
      "rateCardRowMaxKg": null,
      "rateCardRowMaxCbm": null,
      "rateCardBasePrice": 40.0,
      "rateCardFuelSurchargeRate": 0.1,
      "rateCardFuelSurchargeAud": 4.0,
      "rateCardInterstateFromCityCode": "",
      "rateCardInterstateToCityCode": "",
      "rateCardInterstateRatePerCbm": null,
      "rateCardInterstateBillableCbm": null,
      "rateCardInterstateFeeAud": 0.0,
      "rateCardLocalPricePerCbm": 40.0,
      "rateCardLocalMinimumCharge": 40.0,
      "rateCardLocalBillableCbm": 1.0,
      "actualLeavePortTime": "2026-03-08",
      "planPickupTime": "2026-04-07",
      "planArrivedPortTime": "2026-03-25",
      "actualArrivedPortTime": "2026-03-28",
      "importClearanceTime": "",
      "pickupTimeBasis": "merged_auto_order_same_address",
      "pickupTimeLabel": "确定提货时间",
      "pickupTimeStatus": "confirmed",
      "pickupTimeColor": "green",
      "expectedPickupTime": "2026-04-07 10:00",
      "autoOrderEligibilityBasis": "planned_load_time_and_delivery_provider_aulala",
      "autoOrderEligibilityTriggerTime": "2026-03-02 00:00",
      "autoOrderEligibilityReason": "planned_load_time=2026-03-02 00:00 and tad.refName=AULALA",
      "configuredDeliveryProvider": "AULALA",
      "clearanceStatus": "clean",
      "clearanceStatusRaw": "clean",
      "clearanceStatusLabel": "已放行",
      "chargeCode": "",
      "refId": "",
      "provider": "MERGED",
      "source": "fbadidi-live-crowdfund-api-merged",
      "sourceRefreshedAt": "2026-04-06 11:57:38",
      "showClearanceSuffix": false,
      "isMergedOrder": true,
      "mergedOrderCount": 7,
      "mergedOrderCodes": [
        "QY06001642MEL1",
        "QY06001643MEL1",
        "QY06001667MEL1",
        "QY06001677MEL1",
        "QY06001682MEL1",
        "QY06001685MEL1",
        "QY06001687MEL1"
      ],
      "mergedChildOrders": [
        {
          "orderCode": "QY06001642MEL1",
          "pieces": 8,
          "pallets": 1,
          "weightKg": 132.4,
          "cbm": 0.7,
          "price": 44.0,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001643MEL1",
          "pieces": 4,
          "pallets": 1,
          "weightKg": 50.0,
          "cbm": 0.2,
          "price": 44.0,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001667MEL1",
          "pieces": 2,
          "pallets": 1,
          "weightKg": 30.7,
          "cbm": 0.23,
          "price": 44.0,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001677MEL1",
          "pieces": 4,
          "pallets": 2,
          "weightKg": 99.0,
          "cbm": 2.0,
          "price": 88.0,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001682MEL1",
          "pieces": 1,
          "pallets": 1,
          "weightKg": 14.4,
          "cbm": 0.14,
          "price": 24.67,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001685MEL1",
          "pieces": 2,
          "pallets": 1,
          "weightKg": 30.6,
          "cbm": 0.23,
          "price": 44.0,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        },
        {
          "orderCode": "QY06001687MEL1",
          "pieces": 2,
          "pallets": 1,
          "weightKg": 1.0,
          "cbm": 0.17,
          "price": 41.8,
          "clearanceStatusLabel": "已放行",
          "remarks": ""
        }
      ],
      "mergeLabel": "平台自动合并单（7票）",
      "remarks": "平台自动合并单，共7票：QY06001642MEL1、QY06001643MEL1、QY06001667MEL1、QY06001677MEL1、QY06001682MEL1、QY06001685MEL1、QY06001687MEL1"
    }
  ]
};
